version: "3.2"

services:
  oracle:
    image: daerepository03.eur.ad.sag:4443/ccdevops/oracle:11.1
    environment: 
      - ORACLE_ALLOW_REMOTE=true

  is1:
    image: daerepository03.eur.ad.sag:4443/ccdevops/integration-server:$TAG # target image
    ports:
      - 5555

  is2:
    image: daerepository03.eur.ad.sag:4443/ccdevops/integration-server:$TAG # target image
    ports:
      - 5555

  init: # init container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-client:$TAG-antcc
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ../../environments/:/src/environments/
    environment: 
      - CC_SERVER=cc
      - CC_ENV=dev   
    command:
      antcc waitnodes oracledb -Dnodes=is1:sag-is-cluster_is1_1,is2:sagiscluster_is2_1
    depends_on: 
      - oracle
      - is1
      - is2

networks:
  default:
    external:
      name: sagdevops-templates_default
