#!/bin/sh -e

NODE_ALIAS=${1:-node}
RUNTIME_COMPONENT_ID=${2:-OSGI-SPM}
TEMPLATE_ALIAS=${3:-my-template}
PREFIX=${4:-my}

if [ "$#" -lt 2 ]; then
    echo ""
    echo "Usage: $0 <nodeAlias> <componentId> <templateAlias> <prefix>"
    echo ""
    echo "Command Central generate template tool"
    echo ""
    echo "Parameters:"
    echo "  nodeAlias       Node lias to export from. Default ($NODE_ALIAS). One of these:"
    ./sagccw list landscape nodes properties=alias includeHeaders=false
    echo "  componentId     Runtime Component Id to export from $NODE_ALIAS. Default ($RUNTIME_COMPONENT_ID). One of these:"
    ./sagccw list inventory components nodeAlias=$NODE_ALIAS properties=runtimeComponent.id,runtimeComponent.displayName
    echo "  templateAlias   Template alias to generate, default ($TEMPLATE_ALIAS)"
    echo "  prefix          Parameters prefix. Default ($PREFIX)"
    echo ""
    exit 1
fi

echo "Generating '$TEMPLATE_ALIAS' template ..."

if ./sagccw exec templates composite generate nodeAlias=$NODE_ALIAS parameterize=true options=CONFIGURATION overwrite=true alias=$TEMPLATE_ALIAS runtimeComponentId=$RUNTIME_COMPONENT_ID paramPrefix=$PREFIX -a application/yaml ; then
    echo ""
    echo "Generation of '$TEMPLATE_ALIAS' SUCCESSFULL"
    echo ""
    echo "The template file: ./templates/$TEMPLATE_ALIAS/template.yaml"
    echo ""
    echo "Supported parameters and default values are:"
    echo ""
    ./sagccw list templates composite properties $TEMPLATE_ALIAS
    echo ""
    echo "Apply the template, optionally customizing parameter values:"
    echo "./applyw $TEMPLATE_ALIAS nodes=node1,node2 [ <paramName>=<nonDefaultValue> ... ]"
    echo ""
else
    echo ""
    echo "ERROR: generation of '$TEMPLATE_ALIAS' FAILED !"
    echo ""
    ./sagccw get diagnostics logs local OSGI-CCE default.log tail lines=50
    exit 100
fi
