#!/bin/sh

TEMPLATE_ALIAS=$1
DIRNAME=`dirname $0`

shift
PARAMS=$*
echo "Apply template $TEMPLATE_ALIAS with $PARAMS"

export COMPOSE_FILE=$DIRNAME/docker-compose.yml

# docker-compose pull cc
docker-compose up -d cc

echo ""
echo "===================================================================="
echo "Command Central Web UI: https://`docker-compose -f $DIRNAME/docker-compose.yml port cc 8091`"
echo "NOTE: it takes up to a minute to become available"
echo "===================================================================="
echo ""

docker-compose exec \
    cc bash -c \
    "cd /opt/sagtools/profiles/CCE/data/templates/composite/$TEMPLATE_ALIAS; if /opt/sagtools/provision.sh $TEMPLATE_ALIAS $PARAMS; then if [ -f test.sh ]; then ./test.sh ; fi; fi"

echo "===================================================================="
echo "Command Central Web UI: https://`docker-compose -f $DIRNAME/docker-compose.yml port cc 8091`"
echo "===================================================================="
