version: "3.2"

services:
  # # provisioner
  # provision:
  #   image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:10.3
  #   entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
  #   volumes: 
  #     - ./:/src/ # required
  #   environment:
  #     - __ninja_memory_max=256          # template test specific param
  #     - REPO_HOST=aquarius-bg.eur.ad.sag
  #     - REPO_PRODUCT=CC_PI_103oct2018
  #     - REPO_FIX=QARepo
  
  # target container
  ninja:
    image: daerepository03.eur.ad.sag:4443/ccdevops/ninja:$TAG # target image
    build:
      context: .
      dockerfile: Dockerfile            # instructions to build image
      args:
        - TAG
        - __ninja_memory_max=256        # template test specific param
        - REPO_HOST=aquarius-bg.eur.ad.sag
        - REPO_PRODUCT=CC_PI_103oct2018
        - REPO_FIX=QARepo
    ports:
      - 4444                            # container specific ports
    hostname: ninja
    environment:
      - CC_AUTO_REGISTER=1              # No auto register as we don't have a server
    # volumes:
    #   - ./entrypoint.sh:/opt/softwareag/entrypoint.sh # for dev only to avoid image rebuild
    #   - ./test.sh:/test.sh # for dev only to avoid image rebuild

networks:
  default:
    external:
      name: sagdevops-templates_default
