ARG BUILDER_IMAGE
ARG BASE_IMAGE
FROM $BUILDER_IMAGE as builder
FROM $BASE_IMAGE

EXPOSE 4444 4445 4446 4447
ENV SAG_HOME=/opt/softwareag

# copy only minimum
COPY --from=builder $SAG_HOME/NINJA/ $SAG_HOME/NINJA/
COPY --from=builder $SAG_HOME/profiles/NINJA_default/ $SAG_HOME/profiles/NINJA_default/
COPY --from=builder $SAG_HOME/WS-Stack/ $SAG_HOME/WS-Stack/
COPY --from=builder $SAG_HOME/common/ $SAG_HOME/common/

ENTRYPOINT $SAG_HOME/profiles/NINJA_default/bin/console.sh
