version: "3.2"

services:
  # this is the sqlserver itself
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MaNaGe123

  # provisioner for webm db schemas using template.yaml
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-client:10.3
    command: >
      sagcc exec templates composite apply sag-db-sqlserver 
        repo.product=products repo.fix=fixes
        release=10.3 nodes=node db.host=sqlserver db.admin.password=MaNaGe123 --wait-for-cc --wait 600 --sync-job
    # volumes: 
    #   - ./:/src/ # required for accessing .properties file
    depends_on: 
      - sqlserver

  # tester for webm db schemas
  test:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-client:10.3
    command: >
      sagcc list administration product node DatabaseComponentConfigurator  
        database catalog db.type=sqlserver db.username=webm  
        db.password=webm db.name=webm db.url="jdbc:wm:sqlserver://sqlserver:1433;databaseName=webm"
        -e "ISI & MWS & PRE"
    depends_on: 
      - sqlserver

networks:
  default:
    external:
      name: sagdevops-templates_default
